### ISSUE TITLE
Decrypting PreKey message after session creation

### ISSUE THREAD

**Issue by justindthomas** [matrix-org/vodozemac#96]
I'm building a working understanding of this library, but am stuck on one relatively minor issue. I can exchange keys, set up the sessions as necessary (`create_outbound` and `create_inbound` with the `PreKey` message). And then I can pass messages using the established sessions without any problem.

I'm storing the messages encrypted, and will need to re-decrypt them when displayed to the user later. How do I decrypt the `PreKey` message again, after the session has been established? I don't think I want to use `create_inbound` to create a new session - I already have one. I tried just passing the `PreKey` message to the `session.decrypt` method, but that doesn't work (it complains there's no key for message 0).

**Comment by justindthomas** [comment]
It actually looks more like that as the ratchet progresses, the earlier messages can no longer be decrypted by the session. Is that an accurate description of the way this is supposed to operate? I read through the Olm protocol description quickly and that wasn't clear to me.

If that is indeed how it works, I can manage it. I'll just need to store and secure a separate history of messages.

**Comment by justindthomas** [comment]
This is probably the relevant bit:

> If the $j$ of the message is less than the current chain index on the receiver then the message may only be decrypted if the receiver has stored a copy of the message key $M_{i,j}$. Otherwise the receiver computes the chain key, $C_{i,j}$. The receiver computes the message key, $M_{i,j}$, from the chain key and attempts to decrypt the cipher-text, $X_{i,j}$.

...so I probably need to figure out how to store copies of the message keys.

**Comment by poljar** [comment]
> It actually looks more like that as the ratchet progresses, the earlier messages can no longer be decrypted by the session. Is that an accurate description of the way this is supposed to operate?

Yes, a `Session` will by design discard individual message keys once they have been successfully used to decrypt a given message.

This ensures that, in the case that the `Session` gets compromised, your messages that might have been intercepted and collected by an adversary can't be decrypted anymore.

If such a property isn't desirable then perhaps `Session` isn't what you are looking for.

> ...so I probably need to figure out how to store copies of the message keys. Is there a way to access that? The decrypt method only spits back a byte array and I don't see a separate Session implementation that might give me that computed value. Or for that matter, I don't see a method of using an out-of-sequence key to decrypt something.

There isn't a method to manually fetch out and remove individual message keys for decryption. There is one, a fairly hidden one, to do the same for encryption:

https://github.com/matrix-org/vodozemac/blob/5ece305c39a5ca29f4863bbb4a032b732661aa61/src/olm/session/mod.rs#L267

Generally the double ratchet isn't designed to support re-decryption and once you add it in you will need to store a lot of message keys. Not to mention that you open yourself up to replay attacks and change the cryptographic properties and guarantees it offers.

**Comment by justindthomas** [comment]
Okay, thanks for the confirmation. I've started modifying my design to support those constraints (i.e., treating the encrypted messages as ephemeral intended to facilitate transmission only and moving the decrypted data in to a separately encrypted facility for long-term availability).

**Comment by poljar** [comment]
> Okay, thanks for the confirmation. I've started modifying my design to support those constraints (i.e., treating the encrypted messages as ephemeral intended to facilitate transmission only and moving the decrypted data in to a separately encrypted facility for long-term availability).

That's exactly what's happening in Matrix as well, we use the `Session` object to transfer the `GroupSession` objects around, which do support re-decryption (it's actually `InboundGroupSession` that is supporting that, while `GroupSession` is only for encryption).
